# data config
train_dir: "data/wcdataset/train"
test_dir: "data/wcdataset/test"
num_class: 6

# model config
batch_size: 8
learning_rate: 0.001
momentum: 0.9
weight_decay: 5e-4
num_epoch: 100
resize_size: 448
crop_size: 448